insert into Movies (title, releaseDate) values ('Face', '2019-06-29');
insert into Movies (title, releaseDate) values ('Syrup', '2019-05-21');
insert into Movies (title, releaseDate) values ('Chances Are', '2023-03-09');
insert into Movies (title, releaseDate) values ('Drones', '2022-06-19');
insert into Movies (title, releaseDate) values ('Ballad of Nessie, The', '2023-08-20');
insert into Movies (title, releaseDate) values ('Cool Runnings', '2018-12-03');
insert into Movies (title, releaseDate) values ('Wedding in Blood (Noces rouges, Les)', '2020-10-19');
insert into Movies (title, releaseDate) values ('Paris Blues', '2021-07-18');
insert into Movies (title, releaseDate) values ('On Moonlight Bay', '2019-07-14');
insert into Movies (title, releaseDate) values ('Autohystoria', '2021-08-03');
insert into Movies (title, releaseDate) values ('Dakota', '2021-05-14');
insert into Movies (title, releaseDate) values ('Sixpack (Pussikaljaelokuva)', '2022-03-23');
insert into Movies (title, releaseDate) values ('Sleepover', '2021-04-01');
insert into Movies (title, releaseDate) values ('Déjà Vu', '2019-08-12');
insert into Movies (title, releaseDate) values ('Mean Season, The', '2020-04-03');
insert into Movies (title, releaseDate) values ('Babes in Toyland', '2019-02-04');
insert into Movies (title, releaseDate) values ('Deliver Us from Evil', '2022-04-07');
insert into Movies (title, releaseDate) values ('Public Speaking', '2021-06-29');
insert into Movies (title, releaseDate) values ('Red Tails', '2023-05-31');
insert into Movies (title, releaseDate) values ('If God Is Willing and da Creek Don''t Rise', '2020-06-17');
